### ISSUE TITLE
Seria possível adicionar compatibilidade com a nova D175 BT?

### ISSUE THREAD

**Issue by felipesalomao** [wirecardBrasil/maquininha-wirecard-sdk-android#4]
Opa, seria possível adicionar como opção compatibilidade co.mpos pax D175 BT, essa nova maquininha além de visor maior e retroumonado suporta nfc para pagamentos por aproximação. Isso resolve uma importante limitação que a pax 150 e Mp5 tinham..

**Comment by hiagodotme** [comment]
@felipesalomao com a SDK 6.0.0 o suporte da `D175 BT` já é permitido. Acredito que a sua issue já possa ser fechada. ;)
