### ISSUE TITLE
Quais as exceções do proguard para v6?

### ISSUE THREAD

**Issue by hiagodotme** [wirecardBrasil/maquininha-wirecard-sdk-android#6]
@andre-bahia gostaria de saber quais exceções devo adicionar ao proguard para essa nova versão funcionar.

**Comment by hiagodotme** [comment]
@andre-bahia

**Comment by andre-bahia** [comment]
@hiagodotme
Irei adicionar na documentação.
Obrigado por ter levantado esse ponto 👍

**Comment by andre-bahia** [comment]
Documentação atualizada @hiagodotme 
https://github.com/wirecardBrasil/maquininha-wirecard-sdk-android#exce%C3%A7%C3%B5es-proguard
💯

**Comment by hiagodotme** [comment]
Show @andre-bahia valeeeu!
