### ISSUE TITLE
Terminais Compativeis

### ISSUE THREAD

**Issue by Eonassis** [wirecardBrasil/maquininha-wirecard-sdk-android#9]
Poderia nos fornecer uma lista de terminais compativeis com o novo SDK?

**Comment by hiagodotme** [comment]
@Eonassis eu testei aqui com a D150 e com a minizinhaNFC e as duas funcionaram (inclusive o NFC). Como eles estão fazendo uso do PugPag agora, acredito que [essa lista](https://dev.pagseguro.uol.com.br/docs/plugpag-dispositivos-suportados) deveria ser a lista atualizada porém nela não consta a minizinha.

**Comment by Eonassis** [comment]
@hiagodotme muito obrigado amigo, isso deixou meu dia mais feliz

**Comment by Eonassis** [comment]
@hiagodotme eu tentei transacionar com a PAX D150 e nao foi, ja com a minizinhaNFC foi. voce conseguiu transacionar com a D150?? a lista do plugpag ta desatualizada, eu acredito, implementei um blank no plugpag e a minizinha nao foi, so na NFC mesmo

**Comment by hiagodotme** [comment]
@Eonassis estranho, comigo foi normal...

**Comment by Eonassis** [comment]
@hiagodotme a D150 que vc usa e Amarela ou e azul ou preta? voce sabe me dizer? a minha aqui, conecta, pede pra inserir o cartao, em seguida pede pra remover.
I/ContentValues: Status ORDER_CREATED
I/ContentValues: Status PROCESSING
I/ContentValues: Status WAITING_CARD
I/ContentValues: Status INSERTED_CARD
I/ContentValues: Status WAITING_CARD_REMOVAL
I/ContentValues: Status REMOVED_CARD
I/ContentValues: Status COMPLETED_SALE
I/ContentValues: erro na transaçãoMoip Error{code='POS-038', path='', description='Ocorreu um erro ao realizar a transação'}

**Comment by hiagodotme** [comment]
@Eonassis A azul.. Minha mãe tem MP e eu tinha a máquina dela pareada, o o método que retorna os pinpads disponíveis retornou ela aí eu tentei por curiosidade.. Mas não passa ELO, BB nem Itaú.

**Comment by Eonassis** [comment]
@hiagodotme pode ser isso vou tentar vlw, eu tava tentando elo kkkk

**Comment by Eonassis** [comment]
@hiagodotme valewwwww foi aki, em valew pela ajuda amigo

**Comment by hiagodotme** [comment]
Showw @Eonassis acredito que essa issue já possa ser fechada =)
